version: 2.1
orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0
  docker: circleci/docker@2.2.0
  codecov: codecov/codecov@3.2.4
workflows:
  Build app:
    jobs:
      - node/run:
          npm-run: lint
          name: Lint
      - node/run:
          name: Build
          npm-run: build
      - node/test:
          name: Unit test
          pre-steps:
            - browser-tools/install-chrome
          override-ci-command: npm link @angular/cli && npm test -- --no-watch --code-coverage --reporters=coverage,junit,progress,kjhtml
          post-steps:
            - codecov/upload
            - store_test_results:
                name: Store test results
                path: ~/project/reports
            - store_artifacts:
                name: Store coverage report
                path: ~/project/coverage
      - docker/hadolint:
          name: Docker lint
      - docker/publish:
          name: Docker build
          deploy: false
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
      - docker/publish:
          name: Docker publish
          deploy: true
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
          requires:
            - Lint
            - Build
            - Unit test
            - Docker lint
            - Docker build
          filters:
            branches:
              only: "main"
