version: 2.1
orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.1
  docker: circleci/docker@2.2.0
  codecov: codecov/codecov@3.2.4
jobs:
  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.16.0-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm test -- --no-watch --code-coverage --reporters=coverage,junit,progress,kjhtml
      - codecov/upload
      - store_test_results:
          name: Store test results
          path: ~/project/reports
      - store_artifacts:
          name: Store test html report
          path: ~/project/coverage
workflows:
  Build app:
    jobs:
      - node/run:
          npm-run: lint
          name: Lint
      - node/run:
          name: Build
          npm-run: build
      - test:
          name: Unit test
      - docker/hadolint:
          name: Docker lint
      - docker/publish:
          name: Docker build
          deploy: false
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
      - docker/publish:
          name: Docker publish
          deploy: true
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
          requires:
            - Lint
            - Build
            - Unit test
            - Docker lint
            - Docker build
          filters:
            branches:
              only: "main"
