version: 2.1
orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0
jobs:
  lint:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.12.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run: npm run test -- --no-watch --no-progress --reporters=junit,coverage
      - store_test_results:
          name: Store test results
          path: ~/project/reports
      - store_artifacts:
          name: Store covarage report
          path: ~/project/coverage/bss-web
workflows:
  version: 2
  all:
    jobs:
      - lint
      - build
      - test
