version: 2.1
orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0
  docker: circleci/docker@2.2.0
jobs:
  lint:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run lint
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run build
  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.12.1-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run test -- --no-watch --no-progress --reporters=junit,coverage
      - store_test_results:
          name: Store test results
          path: ~/project/reports
      - store_artifacts:
          name: Store covarage report
          path: ~/project/coverage/bss-web
workflows:
  Build app:
    jobs:
      - lint:
          name: Lint
      - build:
          name: Build
      - test:
          name: Unit test
      - docker/hadolint:
          name: Docker lint
      - docker/publish:
          name: Docker build
          deploy: false
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
      - docker/publish:
          name: Docker publish
          deploy: true
          image: bsstudio/bss-web-admin-frontend
          registry: ghcr.io
          tag: latest
          use-buildkit: true
          use-docker-credentials-store: true
          requires:
            - Lint
            - Build
            - Unit test
            - Docker lint
            - Docker build
          filters:
            branches:
              only: "main"
